heat_template_version: 2018-08-31

description: server base template

parameters:
  availability_zone: {type: string}
  flavor: {type: string}
  floating_network: {type: string, default: None}
  image: {type: string}
  key_name: {type: string}
  metadata: {type: json, default: '{}'}
  name: {type: string}
  network: {type: string}
  networks: {type: json, default: []}
  security_groups: {type: json}
  ssh_authorized_keys: {type: json, default: []}
  timezone: {type: string, default: Australia/Sydney}
  volume_size: {type: number, default: 0}
  volume_type: {type: string, default: standard}
  zone: {type: string, default: None}

conditions:
  attachFloatingIP: {not: {equals: [{get_param: floating_network}, None]}}
  attachVolume: {not: {equals: [{get_param: volume_size}, 0]}}
  createDnsRR:
    and:
      - {not: {equals: [{get_param: zone}, None]}}
      - attachFloatingIP

resources:
  port:
    type: OS::Neutron::Port
    properties:
      name: {get_param: name}
      network: {get_param: network}
      security_groups: {get_param: security_groups}

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: floating_network}
      dns_domain: abird.cloud.edu.au.
      dns_name: {get_param: name}
      port_id: {get_resource: port}
    condition: attachFloatingIP

  dns_rr:
    type: OS::Designate::RecordSet
    properties:
      records:
        - {get_attr: [floating_ip,floating_ip_address]}
      type: A
      zone: {str_replace: {template: "${ZONE}.", params: {"${ZONE}": {get_param: zone}}}}
      name: {str_replace: {template: "${NAME}.", params: {"${NAME}": {get_param: name}}}}
    condition: createDnsRR

  volume:
    type: OS::Cinder::Volume
    condition: attachVolume
    properties:
      availability_zone: {get_param: availability_zone}
      description: ""
      metadata: {get_param: metadata}
      name: {get_param: name}
      size: {get_param: volume_size}
      volume_type: {get_param: volume_type}

  volumeAttachment:
    type: OS::Cinder::VolumeAttachment
    condition: attachVolume
    properties:
      instance_uuid: {get_resource: server}
      volume_id: {get_resource: volume}

  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      availability_zone: {get_param: availability_zone}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      name: {get_param: name}
      networks:
        list_concat:
          - [{port: {get_resource: port}}]
          - {get_param: networks}
      user_data:
        str_replace:
          params:
            ${HOSTNAME}: {get_param: name}
            ${TIMEZONE}: {get_param: timezone}
            ${SSH_KEYS}: {get_param: ssh_authorized_keys}
          template: |
            #cloud-config
            bootcmd:
            - echo 'APT::Periodic::Update-Package-Lists "0";' >/etc/apt/apt.conf.d/90auto-upgrades-override
            - echo 'APT::Periodic::Download-Upgradeable-Packages "0";' >>/etc/apt/apt.conf.d/90auto-upgrades-override
            - echo 'APT::Periodic::AutocleanInterval "0";' >>/etc/apt/apt.conf.d/90auto-upgrades-override
            - echo 'APT::Periodic::Unattended-Upgrade "0";' >>/etc/apt/apt.conf.d/90auto-upgrades-override
            fqdn: ${HOSTNAME}
            locale: en_AU.utf8
            timezone: ${TIMEZONE}
            packages:
            - python3
            - python3-pip
            package_reboot_if_required: true
            package_update: true
            package_upgrade: true
            ssh_authorized_keys: ${SSH_KEYS}
            write_files:
            - content: |
                manage_etc_hosts: false
              defer: true
              path: /etc/cloud/cloud.cfg.d/90_user-data-overrides.cfg
      user_data_format: RAW
      user_data_update_policy: IGNORE
